name: caed
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.3.3+2
  flutter_mobx: 
  dio: ^5.6.0
  flutter_modular: ^5.0.3
  result_dart:
  get_it: 
  google_fonts:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mobx_codegen: ^2.1.1
  build_runner: ^2.1.10


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

